version: '3'

services:

  angular:
    image: 'tmvdl/projects:ws'
    build: './src/angular'
    volumes:
      - './src/angular:/app'
    ports:
      - '80:80'

  docker-push:
    image: 'tmvdl/projects:ws'
    build: './src/angular'
