version: '3'

services:
  www:
    build: './src/www'
    volumes:
      - './src/www:/app'
    ports:
      - '8080:80'

  angular:
    image: 'tmvdl/projects:ws'
    build: './src/angular'
    volumes:
      - './src/angular:/app'
    ports:
      - '80:80'

  docker-push:
    image: 'tmvdl/projects:ws'
    build: './src/angular'
